### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by FuryCraft** [MofhyDevs/MofhyCommunity#1]
I propose to add HCaptcha support because actually some bots can automatically create Mofhy accounts. Integrate Site.pro API, there is a repo who do that [MOFHY Lite Site Pro](https://github.com/OverdueWeevil2/mofhylite-sitepro). Support Multi Languages (a simple file where there is all the messages that we can edit). If you want I can help you to translate in french. Add SEO options in the admin panel

**Comment by FuryCraft** [comment]
If possible can support external auth, like Discord, Google, Facebok... and we can choose if we want to use only external auth or the Mofhy auth or the both

**Comment by jaikt** [comment]
This repo has moved to https://github.com/MyOwnFreeHostCommunity/Mofhy. Please create a issue there!
