### ISSUE TITLE
Ummm Maybe its a little bug?But i have no idea to resolve it!

### ISSUE THREAD

**Issue by ImLoadingUuU** [MofhyDevs/MofhyCommunity#2]
`
Fatal error: Cannot redeclare get_gravatar() (previously declared in /home/metooidk/domains/owo/admin/includes/Connect.php:17) in /home/metooidk/domains/owo/includes/Connect.php on line 18`
API settings using HostingHandler.php
 HostingHandler.php Using includes/Connect.php
but apisettings.php using Connect.php from admin
includes/connect.php and admin/includes/connect.php has the same function
so it cause Cannot redeclare get_gravatar()  error! but I have no idea to  resolve it
 ~tottaly not because I'm lazy~
 my English maybe is pretty bad. maybe this issue is hard to read!

**Comment by jaikt** [comment]
This repo has moved to https://github.com/MyOwnFreeHostCommunity/Mofhy. I will fix this issue now, sorry 😭
